var androids = [
  {
    key: "B00OSTKZWM",
    category: "gifts",
    name: "Customized Mask",
    seller: "RCA",
    wholePrice: "57",
    priceFraction: "99",
    stock: 96,
    star: 3,
    starCount: 620,
    img: "https://static.yoursurprise.com/articleimage/groepboxen/86f32074acfc45ce4b59a306d1a5eebe/face-mask_small.jpg?width=263&crop=1%3A1&fbclid=IwAR18KP2Hwmg_S4R3pmPq5xq3fu5254QNb2-ZW0Txz-KjGaT8VHDQc58BB9A",
    url: "https://www.amazon.com/gp/slredirect/picassoRedirect.html/ref=https://www.amazon.com/Nine-West-NW-2044RGPK-Gold-Tone/dp/B072KMX19N/ref=sr_1_10?dchild=1&keywords=gift+item&qid=1623992062&sr=8-10?ie=UTF8&adId=A03332262DHW9SCX1W5WM&url=https%3A%2F%2Fwww.amazon.com%2FRCA-M1-Unlocked-Camera-Android%2Fdp%2FB00OSTKZWM%2Fref%3Dsr_1_1%3Fs%3Delectronics%26ie%3DUTF8%26qid%3D1499124826%26sr%3D1-1-spons%26keywords%3Dandroid%26psc%3D1&qualifier=1499124825&id=1141793968325395&widgetName=sp_atf",
    features: [],
    price: 57.99,
    shipping: 3.99,
  },
  {
    key: "B01H2E0J5M",
    category: "gifts",
    name: "Personalized Engraved Hip Flask-Leather Look",
    seller: "BLU",
    wholePrice: "59",
    priceFraction: "99",
    stock: 5,
    star: 3,
    starCount: 2318,
    img: "https://static.yoursurprise.com/articleimage/bc/bcc1bfcf5a6aeb0baf1116490369a198/hip-flask-leather-look_small.jpg?width=263&crop=1%3A1&fbclid=IwAR2Yvu4wXgkIs3ne_S4jmZNsweqNZDmEuoEkrWz0UoBkKb1gjIG9fPeq5dg",
    url: "https://www.amazon.com/7-Sectional-Assortment-Thanksgiving-Nut-Cravings/dp/B01LOZ311O/ref=sr_1_21?dchild=1&keywords=gift+item&qid=1623999659&sr=8-21",
    features: [],
    price: 59.99,
    shipping: 7.99,
  },
  {
    key: "B0713WPJKX",
    category: "gifts",
    name: " Chocolate",
    seller: "Cell-Tronics",
    wholePrice: "10",
    priceFraction: "99",
    stock: 87,
    star: 4,
    starCount: 3392,
    img: "https://static.yoursurprise.com/articleimage/cd/cd596854d16c5e4d6ee278d4e77ab455/personalised-chocolates-in-gift-tin_small.jpg?width=263&crop=1%3A1&fbclid=IwAR1OpVdWOCCS3XnnpUcs_azV4U_981YQIs0jfbo1SzktuR0FkWd72cP4SAE",
    url: "https://www.amazon.com/Blige-Animal-Rattles-Finders-Butterflies/dp/B06Y22V315/ref=sr_1_23?dchild=1&keywords=gift+item&qid=1623999659&sr=8-23",
    features: [],
    price: 10.99,
    shipping: 3.99,
  },
  {
    key: "B01LPZD1N6",
    category: "gifts",
    name: "Ladies Watch",
    seller: "ATOTO",
    wholePrice: "164",
    priceFraction: "90",
    stock: 20,
    star: 3,
    starCount: 4029,
    img: "https://static.yoursurprise.com/articleimage/ae/aeede2b9b55d61c67a20c150566699c8/wooden-watch_small.jpg?width=263&crop=1%3A1&fbclid=IwAR0Y7gh9G362AqYRqPF2TaqVPExBC6E1ci_Daz_EpheHAoc3_jTRl9TGnP8",
    url: "https://www.amazon.com/Luxury-Little-Diaper-Caddy-Organizer/dp/B07S1DYPT5/ref=sr_1_47?dchild=1&keywords=gift+item&qid=1624029142&sr=8-47",
    features: [],
    price: 164.9,
    shipping: 0,
  },
  {
    key: "B01N1SE4EP",
    category: "gifts",
    name: "Book",
    seller: "NeuTab",
    wholePrice: "49",
    priceFraction: "99",
    stock: 50,
    star: 3,
    starCount: 4947,
    img: "https://static.yoursurprise.com/articleimage/bf/bf475a88086756602d858478abaf9028/dear-daddy_small.jpg?width=263&crop=1%3A1&fbclid=IwAR1xe9ILABlkxiRytESAEyeHfDI44YtlHz47kwneh5TSxFBBALLkfSbtIKs",
    url: "https://www.amazon.com/100-GREETINGS-Happy-Anniversary-Card/dp/B08QPVVN27/ref=sr_1_2?crid=1GRD9B3IU6Q9H&dchild=1&keywords=anniversary+gift+for+her&qid=1624029692&sprefix=annivers%2Caps%2C442&sr=8-2",
    features: [],
    price: 49.99,
    shipping: 7.99,
  },
  {
    key: "B017LDNLIG",
    category: "gifts",
    name: "Special Swipe Shirt",
    seller: "Tracfone",
    wholePrice: "19",
    priceFraction: "94",
    stock: 85,
    star: 3,
    starCount: 381,
    img: "https://static.yoursurprise.com/articleimage/groepboxen/663f358c4a72002322a679eed94dc948/women-s-hoodies_small.jpg?width=263&crop=1%3A1&fbclid=IwAR2PqD2Qs40sz5Y4qA_EMfspKArPSQdLM99jgfqPRvgYkgb4dH-qKpM2LCw",
    url: "https://www.amazon.com/YouNique-Designs-Anniversary-Coffee-Wedding/dp/B07N8SQM4Y/ref=sr_1_33?crid=ABXW7CPAAXY2&dchild=1&keywords=anniversary+gift+for+her+1+year&qid=1624032577&sprefix=anniversary+gift+for+her%2Caps%2C428&sr=8-33",
    features: [],
    price: 19.94,
    shipping: 7.99,
  },
  {
    key: "B018IZ0SWI",
    category: "android",
    name: "BLU Advance 5.0 - Unlocked Dual Sim Smartphone - US GSM - Black",
    seller: "BLU",
    wholePrice: "59",
    priceFraction: "99",
    stock: 10,
    star: 3,
    starCount: 395,
    img: "https://images-na.ssl-images-amazon.com/images/I/41mXjdLezRL._AC_US218_.jpg",
    url: "https://www.amazon.com/BLU-Advance-5-0-Unlocked-Smartphone/dp/B018IZ0SWI/ref=sr_1_7?s=electronics&ie=UTF8&qid=1499124822&sr=1-7&keywords=android",
    features: [
      { description: "Display Size", value: "5 inches" },
      { description: "Computer Memory Size", value: "4 GB" },
      { description: "Operating System", value: "Android" },
      {
        description: "Wireless Communication Technology",
        value: "GSM, 3G, 4G",
      },
      { description: "Cpu Model Speed", value: "1 GHz" },
    ],
    price: 59.99,
    shipping: 3.99,
  },
  {
    key: "B01N4HS7B8",
    category: "android",
    name: "Smart tv box Wechip V5 Android 6.0 Marshmallow 2g 16g Amlogic S905X quad core 4K Dual WiFi",
    seller: "Wechip",
    wholePrice: "53",
    priceFraction: "99",
    stock: 34,
    star: 4,
    starCount: 4740,
    img: "https://images-na.ssl-images-amazon.com/images/I/41q+adG0lNL._AC_US218_.jpg",
    url: "https://www.amazon.com/Smart-Wechip-Android-Marshmallow-Amlogic/dp/B01N4HS7B8/ref=sr_1_8?s=electronics&ie=UTF8&qid=1499124822&sr=1-8&keywords=android",
    features: [],
    price: 53.99,
    shipping: 7.99,
  },

  {
    key: "B072NYXDLY",
    category: "android",
    name: '5.0" Phone Unlocked Dual Sim Quad Core 8GB Android 5.1 Cellphone Gold by TIMMY',
    seller: "Timmy",
    wholePrice: "68",
    priceFraction: "99",
    stock: 14,
    star: 5,
    starCount: 1182,
    img: "https://images-na.ssl-images-amazon.com/images/I/411fzxxuuFL._AC_US218_.jpg",
    url: "https://www.amazon.com/Phone-Unlocked-Android-Cellphone-TIMMY/dp/B072NYXDLY/ref=sr_1_10?s=electronics&ie=UTF8&qid=1499124822&sr=1-10&keywords=android",
    features: [
      { description: "Display Size", value: "5.0 inches" },
      { description: "Operating System", value: "google android" },
    ],
    price: 68.99,
    shipping: 3.99,
  },

  {
    key: "B06XWMQRS6",
    category: "android",
    name: "QacQoc M9C max Android 6.0 Marshmallow TV Box New Amlogic S905X Chipset [2G DDR3/16G eMMC] 4K Smart Box Unlocked 2.4G WIFI Media Player",
    seller: "QacQoc",
    wholePrice: "49",
    priceFraction: "99",
    stock: 54,
    star: 4,
    starCount: 2618,
    img: "https://images-na.ssl-images-amazon.com/images/I/41Sx5HrzuhL._AC_US218_.jpg",
    url: "https://www.amazon.com/QacQoc-Android-Marshmallow-Amlogic-Unlocked/dp/B06XWMQRS6/ref=sr_1_12?s=electronics&ie=UTF8&qid=1499124822&sr=1-12&keywords=android",
    features: [],
    price: 49.99,
    shipping: 3.99,
  },
  {
    key: "B01N41AKT3",
    category: "android",
    name: "Antimi Sweatproof Smart Watch Phone for Android HTC Sony Samsung LG Google Pixel /Pixel and iPhone 5 5S 6 6 Plus 7 Smartphones Black",
    seller: "Antimi",
    wholePrice: "25",
    priceFraction: "99",
    stock: 66,
    star: 3,
    starCount: 3316,
    img: "https://images-na.ssl-images-amazon.com/images/I/41Z3XFc1-5L._AC_US218_.jpg",
    url: "https://www.amazon.com/Antimi-Sweatproof-Android-Samsung-Smartphones/dp/B01N41AKT3/ref=sr_1_13?s=electronics&ie=UTF8&qid=1499124822&sr=1-13&keywords=android",
    features: [
      { description: "Operating System", value: "Android/iOS" },
      { description: "Hardware Platform", value: "Android" },
    ],
    price: 25.99,
    shipping: 3.99,
  },
  {
    key: "B06XY8W1DC",
    category: "android",
    name: "SUNNZO T2 TV Box Streaming Devices for TV/Streaming Media Players Android 6.0 4K WIFI",
    seller: "sunnzo",
    wholePrice: "29",
    priceFraction: "99",
    stock: 97,
    star: 3,
    starCount: 4951,
    img: "https://images-na.ssl-images-amazon.com/images/I/51sZTRzpQjL._AC_US218_.jpg",
    url: "https://www.amazon.com/T2-Streaming-Devices-Players-Android/dp/B06XY8W1DC/ref=sr_1_14?s=electronics&ie=UTF8&qid=1499124822&sr=1-14&keywords=android",
    features: [],
    price: 29.99,
    shipping: 7.99,
  },

  {
    key: "B01JOT42JW",
    category: "gifts",
    name: "Scented candles",
    seller: "GooBang Doo",
    wholePrice: "39",
    priceFraction: "99",
    stock: 54,
    star: 3,
    starCount: 856,
    img: "https://static.yoursurprise.com/articleimage/f9/f9c4dd56c14fe06c999b2750fe62ee04/scented-candles_small.jpg?width=263&crop=1%3A1&fbclid=IwAR1NqVV2Chpze2E5PJaVUk7q2QGng-DjB9CcZAwZHxRxS6UyRL5o57AMJOo",
    url: "https://www.amazon.com/GooBang-Doo-Android-Amlogic-Playing/dp/B01JOT42JW/ref=sr_1_16?s=electronics&ie=UTF8&qid=1499124822&sr=1-16&keywords=android",
    features: [],
    price: 39.99,
    shipping: 3.99,
  },

  {
    key: "B06Y5PY61J",
    category: "android",
    name: "RBSCH M96X Smart Tv Box Android 6.0 Amlogic S905X Quad Core 64bit 2GB / 8GB 4K HD 100Mbps LAN Wifi Mini Home player",
    seller: "RBSCH",
    wholePrice: "44",
    priceFraction: "99",
    stock: 34,
    star: 5,
    starCount: 1151,
    img: "https://images-na.ssl-images-amazon.com/images/I/41c3yiJtjCL._AC_US218_.jpg",
    url: "https://www.amazon.com/RBSCH-Android-Amlogic-100Mbps-player/dp/B06Y5PY61J/ref=sr_1_17?s=electronics&ie=UTF8&qid=1499124822&sr=1-17&keywords=android",
    features: [],
    price: 44.99,
    shipping: 7.99,
  },
  {
    key: "B0182YJ4V6",
    category: "android",
    name: "Yezz Andy 3.5E2 unlocked android phone black",
    seller: "Yezz",
    wholePrice: "37",
    priceFraction: "50",
    stock: 97,
    star: 3,
    starCount: 2770,
    img: "https://images-na.ssl-images-amazon.com/images/I/51PADZ7CaeL._AC_US218_.jpg",
    url: "https://www.amazon.com/Yezz-3-5E2-unlocked-android-phone/dp/B0182YJ4V6/ref=sr_1_18?s=electronics&ie=UTF8&qid=1499124822&sr=1-18&keywords=android",
    features: [
      { description: "Display Size", value: "3.5 inches" },
      { description: "Computer Memory Size", value: "512.0 MB" },
      { description: "Operating System", value: "google android" },
      { description: "Wireless Communication Technology", value: "GSM" },
      { description: "Special Feature", value: "smartphone" },
    ],
    price: 37.5,
    shipping: 7.99,
  },
  {
    key: "B01GL7EB50",
    category: "android",
    name: "Pandawell OTG Micro USB Mobile Phone Fan Portable Dock Cool Cooler Rotating Fan for Samsung Galaxy S7, S7 Edge, LG G5 & Other Android Smart Phone (Black)",
    seller: "Pandawell",
    wholePrice: "4",
    priceFraction: "99",
    stock: 68,
    star: 3,
    starCount: 2806,
    img: "https://images-na.ssl-images-amazon.com/images/I/31Q6QEVwmDL._AC_US218_.jpg",
    url: "https://www.amazon.com/Pandawell-Portable-Rotating-Samsung-Android/dp/B01GL7EB50/ref=sr_1_19?s=electronics&ie=UTF8&qid=1499124822&sr=1-19&keywords=android",
    features: [],
    price: 4.99,
    shipping: 7.99,
  },
  {
    key: "B06XKH29C8",
    category: "android",
    name: "TYD 10.1 inch Tablet Android 6.0 GPS Octa Core 2560X1600 IPS Bluetooth RAM 4GB ROM 64GB 13.0MP 3G Phone Call Tablets PC Dual sim card TYD-107-Black",
    seller: "Tianyida",
    wholePrice: "99",
    priceFraction: "00",
    stock: 95,
    star: 2,
    starCount: 1718,
    img: "https://images-na.ssl-images-amazon.com/images/I/513RoqwKmPL._AC_US218_.jpg",
    url: "https://www.amazon.com/Android-2560X1600-Bluetooth-Tablets-TYD-107-Black/dp/B06XKH29C8/ref=sr_1_20?s=electronics&ie=UTF8&qid=1499124822&sr=1-20&keywords=android",
    features: [
      { description: "Display Size", value: "10.1 inches" },
      { description: "Operating System", value: "Android" },
      { description: "Hard Disk Size", value: "64.0 GB" },
      { description: "Connectivity Technology", value: "usb" },
      { description: "Hardware Platform", value: "android 6.0" },
    ],
    price: 99,
    shipping: 3.99,
  },
  {
    key: "B01MG086CV",
    category: "android",
    name: "[Apple Certified] 3 Feet Coiled Charging Cable for iPhone and Android, YellowKnife 8-Pin Lightning & Micro to USB Date Wire for iPhone 5 6 7 Plus SE, iPad Mini Air iPod, Samsung Sony LG Phones, Black",
    seller: "Yellowknife",
    wholePrice: "11",
    priceFraction: "98",
    stock: 3,
    star: 4,
    starCount: 103,
    img: "https://images-na.ssl-images-amazon.com/images/I/41Htivct16L._AC_US218_.jpg",
    url: "https://www.amazon.com/Certified-Charging-Android-YellowKnife-Lightning/dp/B01MG086CV/ref=sr_1_21?s=electronics&ie=UTF8&qid=1499124822&sr=1-21&keywords=android",
    features: [],
    price: 11.98,
    shipping: 7.99,
  },
  {
    key: "B01MUA1QMU",
    category: "android",
    name: "TracFone Alcatel OneTouch Pixi Eclipse Prepaid Smartphone - Certified Preowned",
    seller: "Tracfone",
    wholePrice: "20",
    priceFraction: "81",
    stock: 66,
    star: 3,
    starCount: 3507,
    img: "https://images-na.ssl-images-amazon.com/images/I/41gV+33qdoL._AC_US218_.jpg",
    url: "https://www.amazon.com/TracFone-Alcatel-OneTouch-Pixi-Eclipse-Prepaid-Smartphone-Certified/dp/B01MUA1QMU/ref=sr_1_22?s=electronics&ie=UTF8&qid=1499124822&sr=1-22&keywords=android",
    features: [
      { description: "Display Size", value: "4" },
      { description: "Display Type", value: "LCD" },
    ],
    price: 20.81,
    shipping: 7.99,
  },
  {
    key: "B015MJLEUS",
    category: "android",
    name: "Anker [3-Pack] PowerLine Micro USB (3ft) - Charging Cable for Samsung, Nexus, LG, Android Smartphones and More (Black)",
    seller: "Anker",
    wholePrice: "10",
    priceFraction: "99",
    stock: 75,
    star: 4,
    starCount: 315,
    img: "https://images-na.ssl-images-amazon.com/images/I/41pKUQFLc8L._AC_US218_.jpg",
    url: "https://www.amazon.com/Anker-3-Pack-PowerLine-Micro-USB/dp/B015MJLEUS/ref=sr_1_23?s=electronics&ie=UTF8&qid=1499124822&sr=1-23&keywords=android",
    features: [],
    price: 10.99,
    shipping: 3.99,
  },
  {
    key: "B06WWPFVNV",
    category: "android",
    name: "Antimi SmartWatch Sweatproof Smart Watch Phone for Android HTC Sony Samsung LG Google Pixel /Pixel and iPhone 5 5S 6 6 Plus 7 Smartphones Black",
    seller: "Antimi",
    wholePrice: "34",
    priceFraction: "99",
    stock: 37,
    star: 4,
    starCount: 1880,
    img: "https://images-na.ssl-images-amazon.com/images/I/51yaeSUl8DL._AC_US218_.jpg",
    url: "https://www.amazon.com/Antimi-SmartWatch-Sweatproof-Android-Smartphones/dp/B06WWPFVNV/ref=sr_1_24?s=electronics&ie=UTF8&qid=1499124822&sr=1-24&keywords=android",
    features: [
      { description: "Operating System", value: "Android/iOS" },
      { description: "Hardware Platform", value: "Android" },
    ],
    price: 34.99,
    shipping: 7.99,
  },
  {
    key: "B00NH2COZC",
    category: "android",
    name: "Native Union NIGHT Cable for Android Devices 10ft Micro-USB to USB Charging Cable (Zebra)",
    seller: "Native Union",
    wholePrice: "39",
    priceFraction: "99",
    stock: 73,
    star: 3,
    starCount: 1894,
    img: "https://images-na.ssl-images-amazon.com/images/I/3167uhg4DPL._AC_US218_.jpg",
    url: "https://www.amazon.com/Native-Union-Android-Micro-USB-Charging/dp/B00NH2COZC/ref=sr_1_25?s=electronics&ie=UTF8&qid=1499124822&sr=1-25&keywords=android",
    features: [],
    price: 39.99,
    shipping: 7.99,
  },
  {
    key: "B01DMVLE7Q",
    category: "android",
    name: 'Samsung Galaxy Tab E Lite 7.0" 8GB (Wi-Fi) Black Accessory Bundle includes Tablet, Cleaning Kit, 3 Stylus Pens and Metal Ear Buds',
    seller: "Samsung",
    wholePrice: "129",
    priceFraction: "99",
    stock: 14,
    star: 4,
    starCount: 1362,
    img: "https://images-na.ssl-images-amazon.com/images/I/51jViuKHqdL._AC_US218_.jpg",
    url: "https://www.amazon.com/gp/slredirect/picassoRedirect.html/ref=pa_sp_btf_electronics_sr_pg1_1?ie=UTF8&adId=A06599961RWOD7JVO4914&url=https%3A%2F%2Fwww.amazon.com%2FSamsung-Galaxy-Accessory-Bundle-Cleaning%2Fdp%2FB01DMVLE7Q%2Fref%3Dsr_1_26%3Fs%3Delectronics%26ie%3DUTF8%26qid%3D1499124822%26sr%3D1-26-spons%26keywords%3Dandroid%26psc%3D1&qualifier=1499124826&id=4777421193755769&widgetName=sp_btf",
    features: [
      { description: "Display Size", value: "7.0 inches" },
      { description: "Computer Memory Size", value: "1.0 GB" },
      { description: "Operating System", value: "Android" },
      { description: "Connectivity Technology", value: "wi-fi" },
      { description: "Wireless Communication Technology", value: "Wi-Fi" },
    ],
    price: 129.99,
    shipping: 7.99,
  },

  {
    key: "B01LPZD1B6",
    category: "gifts",
    name: "Fathers Day Birthday Gifts Keychain for Dad Men Valentines Day Christmas Gifts for Dad Papa Step Father in Law from Girls Kids Step Daughter to Daddy Father and Daughter Never Truly Part Present",
    seller: "ATOTO",
    wholePrice: "99",
    priceFraction: "90",
    stock: 20,
    star: 3,
    starCount: 4029,
    img: "https://m.media-amazon.com/images/I/61pBdQywWSS._AC_UL320_.jpg",
    url: "https://www.amazon.com/Birthday-Keychain-Valentines-Christmas-Daughter/dp/B096XKG2VH/ref=sr_1_2?dchild=1&keywords=key+ring+gifts&qid=1624029747&sr=8-2",
    features: [],
    price: 99.9,
    shipping: 0,
  },
  {
    key: "B01LPZD1V2",
    category: "gifts",
    name: "Harry Potter Gold Snitch Pewter Key Ring",
    seller: "ATOTO",
    wholePrice: "140",
    priceFraction: "90",
    stock: 20,
    star: 3,
    starCount: 4029,
    img: "https://m.media-amazon.com/images/I/817nY8t8HfL._AC_UL320_.jpg",
    url: "https://www.amazon.com/HARRY-POTTER-Gold-Snitch-Pewter/dp/B01J87CRBU/ref=sr_1_7?dchild=1&keywords=key+ring+gifts&qid=1624029747&sr=8-7",
    features: [],
    price: 140.9,
    shipping: 0,
  },
  {
    key: "B01LPZD1G5",
    category: "gifts",
    name: "Marvel Captain America Shield Pewter Key Ring",
    seller: "ATOTO",
    wholePrice: "130",
    priceFraction: "90",
    stock: 20,
    star: 3,
    starCount: 4029,
    img: "https://m.media-amazon.com/images/I/61AVslutMZS._AC_UL320_.jpg",
    url: "https://www.amazon.com/Marvel-Captain-America-Shield-Pewter/dp/B0050B4032/ref=sr_1_22?dchild=1&keywords=key+ring+gifts&qid=1624029747&sr=8-22",
    features: [],
    price: 130.9,
    shipping: 0,
  },
  {
    key: "B01LPZD1G2",
    category: "gifts",
    name: "Lancher Key Chain with (2 Extra Key Rings and Gift Box) Heavy Duty Car Keychain for Men and Women - Black",
    seller: "ATOTO",
    wholePrice: "199",
    priceFraction: "90",
    stock: 20,
    star: 3,
    starCount: 4029,
    img: "https://m.media-amazon.com/images/I/61QWXfW7GwL._AC_UL320_.jpg",
    url: "https://www.amazon.com/Lancher-Chain-Extra-Rings-Keychain/dp/B01IYA1BK0/ref=sr_1_28?dchild=1&keywords=key+ring+gifts&qid=1624029747&sr=8-28",
    features: [],
    price: 199.9,
    shipping: 10,
  },
  {
    key: "B01LPZD1F3",
    category: "gifts",
    name: "2021 Graduation Gift for him for Her Graduation Keychain Gift Set with Genuine Leather Key chain and Card with Inspirational Quote in Gift Packaging Graduation Gift Class of 2021 Ready to Give!",
    seller: "ATOTO",
    wholePrice: "125",
    priceFraction: "00",
    stock: 20,
    star: 3,
    starCount: 4029,
    img: "https://m.media-amazon.com/images/I/51CFoMVocoL._AC_UL320_.jpg",
    url: "https://www.amazon.com/Graduation-Keychain-Genuine-Inspirational-Packaging/dp/B08SCMHJF8/ref=sr_1_31?dchild=1&keywords=key+ring+gifts&qid=1624029747&sr=8-31",
    features: [],
    price: 125.0,
    shipping: 9,
  },
  {
    key: "B01LPZD1S2",
    category: "gifts",
    name: "Keychains Bulk Family Key Ring I Love You To The Moon And Back For Gift",
    seller: "ATOTO",
    wholePrice: "120",
    priceFraction: "90",
    stock: 20,
    star: 3,
    starCount: 4029,
    img: "https://m.media-amazon.com/images/I/617dLUMrAcL._AC_UL320_.jpg",
    url: "https://www.amazon.com/Keychains-Daughter-Brother-Grandma-Grandpa/dp/B073M8LV5R/ref=sr_1_43?dchild=1&keywords=key+ring+gifts&qid=1624029747&sr=8-43",
    features: [],
    price: 120.9,
    shipping: 5,
  },
  {
    key: "B01LPZD1E2",
    category: "gifts",
    name: "Harry Potter Deathly Hallows Pewter Key Ring,Silver",
    seller: "ATOTO",
    wholePrice: "64",
    priceFraction: "76",
    stock: 20,
    star: 3,
    starCount: 4029,
    img: "https://m.media-amazon.com/images/I/81d6+-qJ2DL._AC_UL320_.jpg",
    url: "https://www.amazon.com/HARRY-POTTER-Deathly-Hallows-Pewter/dp/B01J876UHW/ref=sr_1_47?dchild=1&keywords=key+ring+gifts&qid=1624029747&sr=8-47",
    features: [],
    price: 64.76,
    shipping: 5,
  },
  {
    key: "B01LPZD1Z3",
    category: "gifts",
    name: "Coolcos Key Ring Bracelet Wristlet Keychain Bangle Keyring - Portable Leather Tassel Bracelet Keys Holder Women Gift",
    seller: "ATOTO",
    wholePrice: "154",
    priceFraction: "90",
    stock: 20,
    star: 3,
    starCount: 4029,
    img: "https://m.media-amazon.com/images/I/61XS4ofXHKS._AC_UL320_.jpg",
    url: "https://www.amazon.com/Coolcos-Bracelets-Wristlet-Keychain-Keyring/dp/B07SP9LPZY/ref=sr_1_41?dchild=1&keywords=key+ring+gifts&qid=1624029747&sr=8-41",
    features: [],
    price: 154.9,
    shipping: 0,
  },

  {
    key: "B01LPZD1Z2",
    category: "gifts",
    name: "Barnett’s Chocolate Cookies Birthday Gift Basket for Women & Men Gourmet Happy Birthdays Cake Box Arrangements Husband Wife Mom Dad Unique Cookie Baskets Flavors Idea Boyfriend, Girlfriend",
    seller: "ATOTO",
    wholePrice: "150",
    priceFraction: "90",
    stock: 20,
    star: 3,
    starCount: 4029,
    img: "https://m.media-amazon.com/images/I/91ji4E1+RNS._AC_UL320_.jpg",
    url: "https://www.amazon.com/Barnetts-Chocolate-Birthdays-Arrangements-Girlfriend/dp/B093TPSZV1/ref=sr_1_8?dchild=1&keywords=birthday+gift&qid=1624031313&sr=8-8",
    features: [],
    price: 150.9,
    shipping: 5,
  },
  {
    key: "B01LPZD1D4",
    category: "gifts",
    name: "Locket",
    seller: "ATOTO",
    wholePrice: "130",
    priceFraction: "90",
    stock: 20,
    star: 3,
    starCount: 4029,
    img: "https://static.yoursurprise.com/articleimage/9e/9e59724ffd469ca2be209cc9b575698d/name-pendant-square-rhodium_small.jpg?width=263&crop=1%3A1&fbclid=IwAR39N96TuI4qysHuouhziqiyQ9Zu20P7YmJtWE8p85VCvKwW67hXHiRpuMo",
    url: "https://www.amazon.com/Hazel-Creme-Happy-Birthday-Cookie/dp/B07ZSGFPMN/ref=sr_1_9?dchild=1&keywords=birthday+gift&qid=1624031313&sr=8-9",
    features: [],
    price: 130.9,
    shipping: 0,
  },
  {
    key: "B01LPZD1D6",
    category: "gifts",
    name: "Birthday Gifts for Women Spa Gift Box Basket for Wife Mom Sister Girlfriend Best Friend - Thank You Gifts Wine Cup Inspirational Gifts for Women Coworker Friends - Rose Golden",
    seller: "ATOTO",
    wholePrice: "199",
    priceFraction: "90",
    stock: 20,
    star: 3,
    starCount: 4029,
    img: "https://m.media-amazon.com/images/I/81Tb7WGtSHS._AC_UL320_.jpg",
    url: "https://www.amazon.com/Birthday-Basket-Sister-Girlfriend-Friend/dp/B091C2BX2J/ref=sr_1_7?dchild=1&keywords=birthday+gift&qid=1624031313&sr=8-7",
    features: [],
    price: 199.9,
    shipping: 9,
  },
  {
    key: "B01LPZD1P1",
    category: "gifts",
    name: "Birthday Gifts for Women Funny Gifts Baskets Wine Tumbler Gift Basket for Best FriendBFF Mom Daughter Girlfriend Sister Premuim and Unique Happy Birthday Chrismas Gifts Box for Her",
    seller: "ATOTO",
    wholePrice: "155",
    priceFraction: "00",
    stock: 20,
    star: 3,
    starCount: 4029,
    img: "https://m.media-amazon.com/images/I/91y43e44NrL._AC_UL320_.jpg",
    url: "https://www.amazon.com/Birthday-FriendBFF-Daughter-Girlfriend-Chrismas/dp/B08ZSHVSR3/ref=sr_1_10?dchild=1&keywords=birthday+gift&qid=1624031313&sr=8-10",
    features: [],
    price: 155.0,
    shipping: 10,
  },

  {
    key: "B01LPZD1E9",
    category: "gifts",
    name: "Birthday Gift Basket for Men, Women Happy Birthday Gifts for Mom and Dad Friends Birthday Gift for Best Friend Happy Birthday Care Package for College Students for All Ages Fantastic for Party",
    seller: "ATOTO",
    wholePrice: "125",
    priceFraction: "00",
    stock: 20,
    star: 3,
    starCount: 4029,
    img: "https://m.media-amazon.com/images/I/91P4gub8A0L._AC_UL320_.jpg",
    url: "https://www.amazon.com/Birthday-Friends-Package-Students-Fantastic/dp/B08WN7PWZ5/ref=sr_1_18?dchild=1&keywords=birthday+gift&qid=1624031313&sr=8-18",
    features: [],
    price: 125.0,
    shipping: 5,
  },

  {
    key: "B01LPZD1V3",
    category: "gifts",
    name: "Sister Gifts from Sister - Birthday Gifts for Sister",
    seller: "ATOTO",
    wholePrice: "124",
    priceFraction: "55",
    stock: 20,
    star: 3,
    starCount: 4029,
    img: "https://m.media-amazon.com/images/I/91+qaActKJL._AC_UL320_.jpg",
    url: "https://www.amazon.com/Sister-Gifts-Birthday-Relaxing-Tumbler/dp/B08XY9YTBB/ref=sr_1_17?dchild=1&keywords=birthday+gift&qid=1624031313&sr=8-17",
    features: [],
    price: 124.55,
    shipping: 0,
  },

  {
    key: "B01LPZD1S0",
    category: "gifts",
    name: "Amazon.com Gift Card in a Premium Gift Box",
    seller: "ATOTO",
    wholePrice: "99",
    priceFraction: "90",
    stock: 20,
    star: 3,
    starCount: 4029,
    img: "https://m.media-amazon.com/images/I/914QlGL3AnL._AC_UL320_.jpg",
    url: "https://www.amazon.com/Amazon-com-Gift-Card-Premium-Gold/dp/B06ZYZ1TKK/ref=sr_1_4?dchild=1&keywords=anniversary+gift&qid=1624032136&sr=8-4",
    features: [],
    price: 99.9,
    shipping: 5,
  },

  {
    key: "B01LPZD1D5",
    category: "gifts",
    name: "Happy Anniversary Couples Game to Start Awesome Conversations 100+ Cards Gifts for Husband and Wife Him and Her",
    seller: "ATOTO",
    wholePrice: "129",
    priceFraction: "55",
    stock: 20,
    star: 3,
    starCount: 4029,
    img: "https://m.media-amazon.com/images/I/71UwK-ltiKL._AC_UL320_.jpg",
    url: "https://www.amazon.com/Anniversary-Couples-Awesome-Conversations-Husband/dp/B08NK5XYJ1/ref=sr_1_5?dchild=1&keywords=anniversary+gift&qid=1624032136&sr=8-5",
    features: [],
    price: 129.55,
    shipping: 0,
  },

  {
    key: "B01LPZD1A3",
    category: "gifts",
    name: "Knock Knock What I Love about You Fill in the Love Book Fill-in-the-Blank Gift Journal, 4.5 x 3.25-Inches",
    seller: "ATOTO",
    wholePrice: "99",
    priceFraction: "55",
    stock: 20,
    star: 3,
    starCount: 4029,
    img: "https://m.media-amazon.com/images/I/81kbmVHUxpL._AC_UL320_.jpg",
    url: "https://www.amazon.com/Knock-What-Love-About-Journal/dp/1601064934/ref=sr_1_6?dchild=1&keywords=anniversary+gift&qid=1624032136&sr=8-6",
    features: [],
    price: 99.55,
    shipping: 5,
  },

  {
    key: "B01LPZD1X4",
    category: "gifts",
    name: "Romantic Couple Figurines in Love , 9Inch Hand Painted Sweet Loving Together Couple Sculpture to Remember Beautiful Moment - Best Gift for Valentine day",
    seller: "ATOTO",
    wholePrice: "130",
    priceFraction: "00",
    stock: 20,
    star: 3,
    starCount: 4029,
    img: "https://m.media-amazon.com/images/I/51Qs8ma+UuL._AC_UL320_.jpg",
    url: "https://www.amazon.com/jinhuoba-Romantic-Figurines-Sculpture-Beautiful/dp/B07Q4RYQCJ/ref=sr_1_8?dchild=1&keywords=anniversary+gift&qid=1624032136&sr=8-8",
    features: [],
    price: 130.0,
    shipping: 0,
  },

  {
    key: "B01LPZD1Q3",
    category: "gifts",
    name: "Preserved Red Real Rose with I Love You Necklace in 100 Languages -Enchanted Rose Flower Gifts for Mom Wife Girlfriend Her on Mothers Day Valentines Day Anniversary Christmas Birthday Gifts for Women",
    seller: "ATOTO",
    wholePrice: "199",
    priceFraction: "00",
    stock: 20,
    star: 3,
    starCount: 4029,
    img: "https://m.media-amazon.com/images/I/71XisScUG3S._AC_UL320_.jpg",
    url: "https://www.amazon.com/Preserved-Enchanted-Girlfriend-Valentines-Anniversary/dp/B08T727CZ6/ref=sr_1_12?dchild=1&keywords=anniversary+gift&qid=1624032136&sr=8-12",
    features: [],
    price: 199.0,
    shipping: 0,
  },

  {
    key: "B01LPZD1R5",
    category: "gifts",
    name: "Shoulder Bag",
    seller: "ATOTO",
    wholePrice: "124",
    priceFraction: "55",
    stock: 20,
    star: 3,
    starCount: 4029,
    img: "https://static.yoursurprise.com/articleimage/groepboxen/ca6967c3c5016644abdcde09096bf942/shoulder-bag_small.jpg?width=263&crop=1%3A1&fbclid=IwAR2yl8XUcQlqdTx2y7zdtC8zI2z5_xmNt8gTVwM8wJbEnq6HwHGC7onvjKQ",
    url: "https://www.amazon.com/Wedding-Anniversary-Gift-Unconditional-Rosie/dp/B01CIAJSPC/ref=sr_1_24?dchild=1&keywords=anniversary+gift&qid=1624032136&sr=8-24",
    features: [],
    price: 124.55,
    shipping: 0,
  },
];

export default androids;
